version: "3.9"
   
services:
  db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgres/data
  web:
    build: .
    command: python /usr/src/task-17-create-basic-application/DjangoWeatherRemider/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/task-17-create-basic-application
    ports:
      - "8000:8000"
    depends_on: 
      - db

volumes:
  postgres_data:

